apiVersion: v1
kind: ConfigMap
metadata:
  name: bulletin-config
  namespace: bulletin
data:
  SPRING_PROFILES_ACTIVE: "prod"
  MANAGEMENT_SERVER_PORT: "9090"
  STORAGE_S3_BUCKET: "projectdevopsdeploy"
  STORAGE_S3_REGION: "ru-central1"
  STORAGE_S3_ENDPOINT: "https://storage.yandexcloud.net"

