apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulletin-app
  namespace: bulletin
  labels:
    app: bulletin-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bulletin-app
  template:
    metadata:
      labels:
        app: bulletin-app
    spec:
      containers:
        - name: app
          image: ruslangilyazov/project-devops-deploy:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: mgmt
              containerPort: 9090
          envFrom:
            - configMapRef:
                name: bulletin-config
            - secretRef:
                name: bulletin-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: mgmt
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: mgmt
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 4

