apiVersion: v1
kind: Secret
metadata:
  name: bulletin-secret
  namespace: bulletin
type: Opaque
stringData:
  # Этот файл — шаблон. Реальные значения в git не кладём.
  SPRING_DATASOURCE_URL: ""
  SPRING_DATASOURCE_USERNAME: ""
  SPRING_DATASOURCE_PASSWORD: ""
  STORAGE_S3_ACCESSKEY: ""
  STORAGE_S3_SECRETKEY: ""

